# This override file should be used when running automated tests so
# that test output is saved to the host

services:
  ? crai-jaf-frontend
  : build:
      target: development
    image: crai-jaf-frontend-development
    container_name: crai-jaf-frontend-test
    command: npm run test
    volumes:
      - ./app:/home/node/app
      - ./test:/home/node/test
      - ./test-output:/home/node/test-output
      - ./jest.config.js:/home/node/jest.config.js
      - ./package.json:/home/node/package.json
