# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  ? crai-jaf-frontend
  : build:
      target: development
    image: crai-jaf-frontend-development
    container_name: crai-jaf-frontend-development
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json
